mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from p_library import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.books_list),
    path('index/', views.index),
    path("index/book_increment/", views.book_increment),
    path("index/book_decrement/", views.book_decrement),
    path("index/redactions/", views.redaction),
    path('p_lib/', include("p_library.urls"))
    # path("authors", views.AuthorListView.as_view(), name="author_list"),
    # path("author/create", views.AuthorCreateView.as_view(), name="author_create"),
]

p_library/urls.py
from django.urls import path
from p_library import views

app_name = "p_library"

urlpatterns = [
    path("authors", views.AuthorListView.as_view(), name="author_list"),
    path("author/create", views.AuthorCreateView.as_view(), name="author_create"),
    path("authors/create_many", views.author_create_many, name='author_create_many'),
    path("authors/create_many_books", views.books_authors_create_many, name="book_author_create_many"),
    path("books_list", views.BooksListView.as_view(), name="books_list"),
    path("book_update<int:pk>", views.BookUpdateView.as_view(), name="book_update_view"),
]

p_library/models.py
from django.db import models

class Author(models.Model):
    full_name = models.TextField()  
    birth_year = models.SmallIntegerField()  
    country = models.CharField(max_length=2)

    class Meta:
        verbose_name = "Authors of book"

    def __str__(self):
        return self.full_name

class Redaction(models.Model):
    name=models.TextField()

    def __str__(self):
        return self.name


class Friend(models.Model):
    name = models.TextField()
    def __str__(self):
        return self.name

class Book(models.Model):
    ISBN = models.CharField(max_length=13)
    title = models.TextField()
    description = models.TextField()
    year_release = models.SmallIntegerField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name="one_author")
    copy_count = models.SmallIntegerField(default=1)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    redaction = models.ForeignKey(Redaction, on_delete=models.CASCADE)
    authors = models.ManyToManyField(
        Author,
        through='Inspiration',
        through_fields=('book', 'author'),
    )
    friend = models.ForeignKey(Friend, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

class Inspiration(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete = models.CASCADE)
    inspirer = models.ForeignKey(
        Author,
        on_delete=models.CASCADE,
        related_name="inspired_works",
        null=True,
    )

p_library/forms.py
from django import forms
from p_library.models import Author, Book

class AuthorForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput)
    class Meta:
        fields = "__all__"
        model = Author

    
class BookForm(forms.ModelForm):
    class Meta:
        fields="__all__"
        model=Book

p_library/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views.decorators.csrf import csrf_exempt
from p_library.models import Book, Redaction
from django.template import loader
from p_library.models import Author
from p_library.forms import AuthorForm, BookForm
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.forms import formset_factory
from django.http.response import HttpResponseRedirect

def books_list(request):
    books = Book.objects.all()
    return HttpResponse(books)

def index(request):
    template = loader.get_template("index.html")
    books = Book.objects.all()
    biblio_data = {"title": "мою библиотеку", 'books': books}
    return HttpResponse(template.render(biblio_data, request))

@csrf_exempt
def book_increment(request):
    if request.method == "POST":
        book_id = request.POST["id"]
        if not book_id:
            return redirect("/index/")
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect("/index/")
            book.copy_count += 1
            book.save()
        return redirect("/index/")
    else:
        return redirect("index/")

@csrf_exempt
def book_decrement(request):
    if request.method == "POST":
        book_id = request.POST["id"]
        if not book_id:
            return redirect("/index/")
        else:
            book = Book.objects.filter(id = book_id).first()
            if not book:
                return redirect("/index/")
            if book.copy_count < 0:
                book.copy_count = 0
            else:
                book.copy_count -= 1
            book.save()
        return redirect("/index/")
    else:
        return redirect("/index/")

def redaction(request):
    template = loader.get_template("redactions.html")
    books = Book.objects.all()
    redactions = Redaction.objects.all()
    books_data = {"books": books, "redactions": redactions}
    return HttpResponse(template.render(books_data))


class AuthorListView(ListView):
    model = Author
    template_name = 'authors_list.html'

class AuthorCreateView(CreateView):
    model = Author
    form_class = AuthorForm
    success_url = reverse_lazy("p_library:author_list")
    template_name = "authors_edit.html"

def author_create_many(request):  
    AuthorFormSet = formset_factory(AuthorForm, extra=2)  #  Первым делом, получим класс, который будет создавать наши формы. Обратите внимание на параметр `extra`, в данном случае он равен двум, это значит, что на странице с несколькими формами изначально будет появляться 2 формы создания авторов.
    if request.method == 'POST':  #  Наш обработчик будет обрабатывать и GET и POST запросы. POST запрос будет содержать в себе уже заполненные данные формы
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')  #  Здесь мы заполняем формы формсета теми данными, которые пришли в запросе. Обратите внимание на параметр `prefix`. Мы можем иметь на странице не только несколько форм, но и разных формсетов, этот параметр позволяет их отличать в запросе.
        if author_formset.is_valid():  #  Проверяем, валидны ли данные формы
            for author_form in author_formset:  
                author_form.save()  #  Сохраним каждую форму в формсете
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))  #  После чего, переадресуем браузер на список всех авторов.
    else:  #  Если обработчик получил GET запрос, значит в ответ нужно просто "нарисовать" формы.
        author_formset = AuthorFormSet(prefix='authors')  #  Инициализируем формсет и ниже передаём его в контекст шаблона.
    return render(request, 'manage_authors.html', {'author_formset': author_formset})

def books_authors_create_many(request):
    AuthorFormSet = formset_factory(AuthorForm, extra=2)
    BooksFormSet = formset_factory(BookForm, extra=2)

    if request.method == "POST":
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix="authors")
        book_formset = BooksFormSet(request.POST, request.FILES, prefix="books")
        if author_formset.is_valid() and book_formset.is_valid():
            for author_form in author_formset:
                author_form.save()
            for book_form in book_formset:
                book_form.save()
            return HttpResponseRedirect(reverse_lazy("p_library:author_list"))
    else:
        author_formset = AuthorFormSet(prefix = "authors")
        book_formset = BooksFormSet(prefix="books")
    return render(request, "manage_books_authors.html", {"author_formset": author_formset, 'book_formset': book_formset})

class BooksListView(ListView):
    template_name = 'books_list.html'
    context_object_name = "books"
    model = Book
    
class BookUpdateView(UpdateView):
    template_name = 'book_update.html'
    model = Book
    fields = ['friend', 'title', 'description', 'author', 'copy_count', 'price',]
    success_url = reverse_lazy("p_library:books_list")

p_library/templates/authors_edit.html
{% extends 'base.html' %}
{% block title %} Форма создания и редактирования Авторов {% endblock %}
{% block main_content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock %}

p_library/templates/authors_list.html
{% extends 'base.html' %}
{% block title %} Список авторов {% endblock %}
{% block main_content %}

    <ul>
        {% for author in object_list %}
            <li>{{author.full_name}}</li>
        {% endfor %}
    </ul>

{% endblock %}

p_library/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
    <title>{%block title%}{% endblock %}</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <script src="{% static 'js/bootstrap.min.js' %} "></script>
  {% block extra_head %}{% endblock %}
</head>

<body>
    <div class="container mt-5">
        {% block main_content %}
        {% endblock %}
    </div>
    

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="{% static 'js/script.js' %} "></script>
</body>

</html>

p_library/templates/book_update.html
{% extends 'base.html' %}
{% block title %}Изменить книгу{% endblock %}
{% block main_content %}

    <form method='post'>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Save">
    </form>

{% endblock %}

p_library/templates/books_list.html
{% extends 'base.html' %}
{% block title %}Список книг{% endblock %}
{% block main_content %}

        <h1 class="display-4">Список книг</h1>
        <ul class="list-group  list-group-flush">
            {% for book in books %}
                <ul class="list-group"><h1 class="h4 text-left font-weight-bold mt-5">{{book.title}}</h1>
                <li class="list-group-item">
                    <p class="font-italic">{{book.author}}</p> 
                    <p class="font-weight-light">{{book.description|truncatechars:200}}</p>
                {% if book.friend %}
                <p>Имя друга, которому передал: <span class="badge badge-secondary">{{book.friend}}</span></p>
                {% endif %}
                <a class='btn btn-primary' href="{% url 'p_library:book_update_view' book.id %}">Изменить книгу</a>
                </ul>
                
            {% endfor %}
        </ul>
   


{% endblock %}

p_library/templates/index.html
Добро пожаловать в {{ title }}.  <br>
Тут собрано {{ books|length }} книг из моей личной коллекции. <br>

<table border="1">
        <thead>
            <tr>
                <th>"Индекс"</th>
                <th>"ISBN"</th>
                <th>"Количество"</th>
                <th>"Название"</th>
                <th>"Дата публикации"</th>
                <th>"Автор"</th>
                <th>"Страна"</th>
                <th>"Краткое описаниеЭ</th>
                <th>"Цена"</th>
            </tr>
        </thead>
    {% for book in books %}
        
        <tbody>
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{book.ISBN}}</td>
                <td>{{book.copy_count}}</td>
                <td>{{book.title}}</td>
                <td>{{ book.year_release }}</td>
                <td>{{ book.author.full_name }}</td>
                <td>{{ book.author.country }}</td>
                <td>{{book.description}}</td>
                <td>{{book.price}} руб.</td>
                <td>
                    <form action="/index/book_increment/" method="post" enctype="multipart/form-data">
                        <input type="hidden" name="id" value="{{book.id}}">
                        <input type="submit" value="Увеличить количество">
                    </form>
                    <form action="/index/book_decrement/" method="post" enctype="multipart/form-data">
                        <input type="hidden" name="id" value="{{book.id}}">
                        <input type="submit" value="Уменьшить количество">
                    </form>
                </td>
            </tr>
        </tbody>
    {% endfor %}
</table>

p_library/templates/manage_authors.html
{% extends 'base.html' %}

{% block title %}Manage Authors{% endblock %}

{% block main_content %}

    <form method="post">
        {{ author_formset.management_form }}
        {% csrf_token %}
        {% for form in author_formset %}
            {{form.as_ul}} <br>
        {% endfor %}
        <input type="submit" value="Save">

    </form>





{% endblock %}

p_library/templates/manage_books_authors.html
{% extends 'base.html' %}
{% block title %}Manage books and authors{% endblock %}
{% block main_content %}

    <form method="post">
        {{author_formset.management_form}}
        {{book_formset.management_form}}
        {% csrf_token %}
        {% for form in author_formset %}
            {{form.as_ul}} <br>
        {% endfor %}

        {% for form in book_formset %}
            {{form.as_ul}}
        {% endfor %}
        <input type="submit" value="Save">
    </form>

{% endblock %}

p_library/templates/redactions.html
{% extends 'base.html' %}

{% block main_content %}

        <h1 class="display-4">Список литературы</h1>
        <ul class="list-group  list-group-flush">
            {% for redaction in redactions %}
                <ul class="list-group"><h1 class="h4 text-left font-weight-bold mt-5">{{redaction}}</h1></ul>
                {% for book in redaction.book_set.all %}
                    <li class="list-group-item list-group-item-action ml-3" >
                        <p class="font-weight-bold">{{book}}</p> <p class="font-italic">{{book.author}}</p> <p class="font-weight-light">{{book.description}}</p>
                        <span {% if book.price <= 1000.0 %}class="badge badge-secondary badge-danger"{% else %}class="badge badge-secondary"{% endif %}>
                                {{book.price}} руб. {% if book.price <= 1000.0 %}СКИДКА!!!!{% endif %}
                        </span> <span class="badge badge-pill badge-warning">{% if book.copy_count == 2 %}Осталось всего {{book.copy_count}} книги {% elif book.copy_count == 1 %}Осталась всего {{book.copy_count}} книга!!! {% endif %}</span></li>
                {% endfor %}
            {% endfor %}
        </ul>
   


{% endblock %}